apiVersion: v1
kind: Service
metadata:
  name: vad-service
spec:
  type: NodePort
  selector:
    app: vad
  ports:
    - protocol: TCP
      port:  8000
      targetPort:  8000
      nodePort: 30080
